# Database connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dev
quarkus.datasource.password=dev123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/procurement

# Ollama Chat Config (Qwen)
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:3b
quarkus.langchain4j.ollama.base-url=http://localhost:11434

quarkus.langchain4j.ollama.embedding-model.model-id=bge-m3

# PGVector Store Setup
quarkus.langchain4j.pgvector.table=procurement_record
quarkus.langchain4j.pgvector.dimension=1024