# Database connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dev
quarkus.datasource.password=dev123
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.8.140:5432/procurement
quarkus.hibernate-orm.database.version-check.enabled=false

# Ollama Chat Config (Qwen)
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:7b
quarkus.langchain4j.ollama.base-url=http://192.168.8.140:11434
quarkus.langchain4j.ollama.timeout=360s
quarkus.langchain4j.ollama.embedding-model.model-id=bge-m3

# Infinispan Store Setup
quarkus.langchain4j.infinispan.cache-name=procurement_embeddings
quarkus.langchain4j.infinispan.dimension=1024
quarkus.langchain4j.infinispan.create-cache=true
quarkus.langchain4j.ollama.chat-model.temperature=0.0
quarkus.langchain4j.infinispan.cache-config=<?xml version=\"1.0\"?><distributed-cache name=\"procurement_embeddings\" mode=\"SYNC\"><persistence><file-store><data path=\"/opt/infinispan/server/data\"/></file-store></persistence><indexing enabled=\"true\" storage=\"local-heap\"><index-reader/><indexed-entities><indexed-entity>LangchainItem1024</indexed-entity></indexed-entities></indexing></distributed-cache>

quarkus.infinispan-client.hosts=192.168.8.140:11222
quarkus.infinispan-client.username=admin
quarkus.infinispan-client.password=password
quarkus.infinispan-client.client-intelligence=BASIC

# logging
quarkus.log.level=INFO
quarkus.log.category."com.edw".level=DEBUG

# ws
quarkus.websockets-next.server.supported-subprotocols=chat

# docling
quarkus.docling.devservices.enabled=false
quarkus.docling.base-url=http://192.168.8.140:5001

# chat memory
quarkus.langchain4j.chat-memory.memory-window.max-messages=10
quarkus.langchain4j.chat-memory.token-window.max-tokens=1000