# Database connection
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=dev
quarkus.datasource.password=dev123
quarkus.datasource.jdbc.url=jdbc:postgresql://192.168.8.140:5432/procurement

# Ollama Chat Config (Qwen)
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:7b
quarkus.langchain4j.ollama.base-url=http://192.168.8.140:11434
quarkus.langchain4j.ollama.timeout=240s
quarkus.langchain4j.ollama.embedding-model.model-id=bge-m3

# PGVector Store Setup
quarkus.langchain4j.pgvector.table=procurement_embeddings
quarkus.langchain4j.pgvector.dimension=1024
quarkus.langchain4j.ollama.chat-model.temperature=0.0

# logging
quarkus.log.level=INFO
quarkus.log.category."com.edw".level=DEBUG

# ws
quarkus.websockets-next.server.supported-subprotocols=chat